
TEMPLATE_CONFIGS = {
    'modern': { 'accent': '#1e293b', 'font': 'Helvetica', 'type': 'standard' },
    'executive': { 'accent': '#1e1b4b', 'font': 'Times New Roman', 'border': True, 'type': 'standard' },
    'creative': { 'accent': '#ec4899', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'academic': { 'accent': '#475569', 'font': 'Times New Roman', 'type': 'standard' },
    'sleek': { 'accent': '#3b82f6', 'font': 'Helvetica', 'type': 'standard' },
    'bold': { 'accent': '#000', 'font': 'Helvetica', 'border': True, 'type': 'bold' },
    'impact': { 'accent': '#ff4757', 'font': 'Helvetica', 'highlight': True, 'type': 'bold' },
    'corporate': { 'accent': '#000', 'font': 'Times New Roman', 'type': 'standard' },
    'midnight': { 'accent': '#3b82f6', 'dark': True, 'font': 'Helvetica', 'type': 'dark' },
    'ruby': { 'accent': '#b33939', 'font': 'Times New Roman', 'type': 'standard' },
    'emerald': { 'accent': '#059669', 'font': 'Helvetica', 'type': 'standard' },
    'indigo': { 'accent': '#4338ca', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'sunset': { 'accent': '#f59e0b', 'font': 'Helvetica', 'gradient': True, 'sidebar': True, 'type': 'split' },
    'clean': { 'accent': '#10b981', 'font': 'Helvetica', 'type': 'standard' },
    'compact': { 'accent': '#000', 'font': 'Helvetica', 'compact': True, 'type': 'standard' },
    'elegant': { 'accent': '#1e293b', 'font': 'Times New Roman', 'serif': True, 'type': 'standard' },
    'startup': { 'accent': '#ff4757', 'font': 'Helvetica', 'startup': True, 'type': 'bold' },
    'classic': { 'accent': '#000', 'font': 'Times New Roman', 'type': 'standard' },
    'modern_dark': { 'accent': '#60a5fa', 'dark': True, 'font': 'Helvetica', 'type': 'dark' },
    'duotone_purple': { 'accent': '#9333ea', 'font': 'Helvetica', 'type': 'standard' },
    'sage_garden': { 'accent': '#708238', 'font': 'Times New Roman', 'type': 'standard' },
    'social_pro': { 'accent': '#1da1f2', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'geometric': { 'accent': '#f43f5e', 'font': 'Helvetica', 'type': 'bold' },
    'cream_peach': { 'accent': '#fb923c', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'spectrum': { 'accent': '#3b82f6', 'font': 'Helvetica', 'gradient': True, 'type': 'standard' },
    'clarity': { 'accent': '#0ea5e9', 'font': 'Helvetica', 'type': 'standard' },
    'spacesmart': { 'accent': '#64748b', 'font': 'Helvetica', 'compact': True, 'type': 'standard' },
    'polished_path': { 'accent': '#1e293b', 'font': 'Helvetica', 'type': 'standard' },
    'flexform': { 'accent': '#4d7c0f', 'font': 'Helvetica', 'type': 'standard' },
    'nextstep': { 'accent': '#b91c1c', 'font': 'Helvetica', 'type': 'bold' },
    'turquoise_corp': { 'accent': '#0d9488', 'font': 'Helvetica', 'type': 'standard' },
    'scholar_line': { 'accent': '#3f3f46', 'font': 'Times New Roman', 'type': 'standard' },
    'collage': { 'accent': '#db2777', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'swiss': { 'accent': '#dc2626', 'font': 'Helvetica', 'caps': True, 'type': 'bold' },
    'data_expert': { 'accent': '#2563eb', 'font': 'Helvetica', 'type': 'standard' },
    'terminal': { 'accent': '#22c55e', 'font': 'Courier', 'dark': True, 'type': 'dark' },
    'lavender': { 'accent': '#8b5cf6', 'font': 'Times New Roman', 'sidebar': True, 'type': 'split' },
    'luxury_gold': { 'accent': '#d4af37', 'font': 'Times New Roman', 'type': 'standard' },
    'silver_lining': { 'accent': '#94a3b8', 'font': 'Helvetica', 'type': 'standard' },
    'navy_seal': { 'accent': '#1e3a8a', 'font': 'Times New Roman', 'type': 'standard' },
    'mint_fresh': { 'accent': '#2dd4bf', 'font': 'Helvetica', 'type': 'standard' },
    'peach_dev': { 'accent': '#fb923c', 'font': 'Helvetica', 'type': 'standard' },
    'autumn': { 'accent': '#92400e', 'font': 'Times New Roman', 'type': 'standard' },
    'sky_gradient': { 'accent': '#0ea5e9', 'font': 'Helvetica', 'sidebar': True, 'gradient': True, 'type': 'split' },
    'charcoal_bold': { 'accent': '#171717', 'font': 'Helvetica', 'caps': True, 'type': 'bold' },
    'minimal_ink': { 'accent': '#000000', 'font': 'Times New Roman', 'caps': True, 'type': 'standard' },
    'classic_journal': { 'accent': '#000000', 'font': 'Times New Roman', 'type': 'standard' },
    'legal_brief': { 'accent': '#1e293b', 'font': 'Times New Roman', 'type': 'standard' },
    'portfolio_plus': { 'accent': '#4338ca', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'careeredge': { 'accent': '#b91c1c', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'pureelegance': { 'accent': '#d1d5db', 'font': 'Times New Roman', 'type': 'standard' },
    'profileprime': { 'accent': '#1e40af', 'font': 'Helvetica', 'type': 'standard' },
    'readease': { 'accent': '#0f172a', 'font': 'Helvetica', 'type': 'standard' },
    'multipro': { 'accent': '#374151', 'font': 'Helvetica', 'type': 'standard' },
    'personaprint': { 'accent': '#7c3aed', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'standout': { 'accent': '#db2777', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'probanner': { 'accent': '#2563eb', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'blendform': { 'accent': '#4b5563', 'font': 'Helvetica', 'type': 'standard' },
    'clearline': { 'accent': '#06b6d4', 'font': 'Courier', 'caps': True, 'type': 'standard' },
    'designmark': { 'accent': '#f97316', 'font': 'Helvetica', 'type': 'standard' },
    'focusform': { 'accent': '#111827', 'font': 'Helvetica', 'type': 'standard' },
    'atspro': { 'accent': '#000000', 'font': 'Helvetica', 'type': 'standard' },
    'streamline': { 'accent': '#059669', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'claritypro': { 'accent': '#0ea5e9', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'inspireform': { 'accent': '#ea580c', 'font': 'Times New Roman', 'type': 'standard' },
    'artistry': { 'accent': '#8b5cf6', 'font': 'Times New Roman', 'type': 'standard' },
    'sharplines': { 'accent': '#0f172a', 'font': 'Helvetica', 'type': 'bold' },
    'designslate': { 'accent': '#475569', 'font': 'Helvetica', 'dark': True, 'type': 'dark' },
    'contentfocus': { 'accent': '#1e293b', 'font': 'Times New Roman', 'type': 'standard' },
    'nursing_pro': { 'accent': '#0891b2', 'font': 'Helvetica', 'type': 'standard' },
    'legal_expert': { 'accent': '#1e1b4b', 'font': 'Times New Roman', 'type': 'standard' },
    'sales_giant': { 'accent': '#b91c1c', 'font': 'Helvetica', 'type': 'bold' },
    'dev_mono': { 'accent': '#10b981', 'font': 'Courier', 'dark': True, 'type': 'dark' },
    'hr_harmonious': { 'accent': '#ec4899', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'retail_star': { 'accent': '#f59e0b', 'font': 'Helvetica', 'type': 'standard' },
    'chef_cuisine': { 'accent': '#1e293b', 'font': 'Times New Roman', 'type': 'standard' },
    'real_estate': { 'accent': '#1d4ed8', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'fitness_coach': { 'accent': '#dc2626', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'travel_guide': { 'accent': '#0369a1', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'hush_minimal': { 'accent': '#94a3b8', 'font': 'Times New Roman', 'caps': True, 'type': 'standard' },
    'stark_white': { 'accent': '#000000', 'font': 'Helvetica', 'type': 'standard' },
    'zen_master': { 'accent': '#1e293b', 'font': 'Times New Roman', 'type': 'standard' },
    'grid_logic': { 'accent': '#4b5563', 'font': 'Courier', 'type': 'standard' },
    'editorial': { 'accent': '#000000', 'font': 'Times New Roman', 'type': 'standard' },
    'vintage_type': { 'accent': '#44403c', 'font': 'Courier', 'type': 'standard' },
    'futuro': { 'accent': '#7c3aed', 'font': 'Helvetica', 'type': 'bold' },
    'soft_focus': { 'accent': '#f472b6', 'font': 'Helvetica', 'type': 'standard' },
    'bold_box': { 'accent': '#000000', 'font': 'Helvetica', 'border': True, 'type': 'bold' },
    'the_minimal': { 'accent': '#6b7280', 'font': 'Helvetica', 'type': 'standard' },
    'impact_plus': { 'accent': '#ef4444', 'font': 'Helvetica', 'type': 'bold' },
    'clean_pro': { 'accent': '#1e293b', 'font': 'Helvetica', 'type': 'standard' },
    'modern_edge': { 'accent': '#3b82f6', 'font': 'Helvetica', 'type': 'standard' },
    'classic_serif': { 'accent': '#1e1b4b', 'font': 'Times New Roman', 'type': 'standard' },
    'modern_grid': { 'accent': '#0f172a', 'font': 'Helvetica', 'type': 'standard' },
    'sidebar_pro': { 'accent': '#1e293b', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'content_king': { 'accent': '#111827', 'font': 'Times New Roman', 'type': 'standard' },
    'value_prop': { 'accent': '#4338ca', 'font': 'Helvetica', 'type': 'standard' },
    'career_map': { 'accent': '#10b981', 'font': 'Helvetica', 'sidebar': True, 'type': 'split' },
    'the_standard': { 'accent': '#1e293b', 'font': 'Helvetica', 'type': 'standard' }
}
