"""restore_plan_and_subscription_fields_for_backwards_compatibility

Revision ID: 8b9570b84902
Revises: dc07ce6bc1e0
Create Date: 2026-02-08 17:27:41.430723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9570b84902'
down_revision = 'dc07ce6bc1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interval', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('credits_per_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rollover_allowed', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_plans_slug', ['slug'])
        batch_op.create_unique_constraint('uq_plans_stripe_price_id', ['stripe_price_id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_subscriptions_stripe_subscription_id', ['stripe_subscription_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subscriptions_stripe_subscription_id', type_='unique')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_subscription_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint('uq_plans_stripe_price_id', type_='unique')
        batch_op.drop_constraint('uq_plans_slug', type_='unique')

        batch_op.drop_column('rollover_allowed')
        batch_op.drop_column('features')
        batch_op.drop_column('credits_per_interval')
        batch_op.drop_column('interval')
        batch_op.drop_column('price')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
