"""Add subscription and credit system tables

Revision ID: dc07ce6bc1e0
Revises: f5dbe4f600b1
Create Date: 2026-02-08 17:01:22.985716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'dc07ce6bc1e0'
down_revision = 'f5dbe4f600b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('ai_usage')
    op.drop_table('subscription_history')
    op.drop_table('subscription')
    op.drop_table('user_credits')
    with op.batch_alter_table('ai_video_interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('amount')
        batch_op.drop_column('feature_name')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('transaction_type')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_plan_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('monthly_credits', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_plans_razorpay_plan_id', ['razorpay_plan_id'])
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('interval')
        batch_op.drop_column('currency')
        batch_op.drop_column('features')
        batch_op.drop_column('credits_per_interval')
        batch_op.drop_column('price')
        batch_op.drop_column('slug')
        batch_op.drop_column('rollover_allowed')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_subscriptions_razorpay_subscription_id', ['razorpay_subscription_id'])
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('cancel_at_period_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('uq_subscriptions_razorpay_subscription_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('razorpay_subscription_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollover_allowed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('credits_per_interval', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('features', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('interval', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('uq_plans_razorpay_plan_id', type_='unique')
        batch_op.drop_column('monthly_credits')
        batch_op.drop_column('monthly_price')
        batch_op.drop_column('razorpay_plan_id')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('metadata_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('feature_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.drop_column('description')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('credits')
        batch_op.drop_column('type')

    with op.batch_alter_table('ai_video_interviews', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    op.create_table('user_credits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=True),
    sa.Column('last_reset_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('old_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('old_plan_id', sa.INTEGER(), nullable=True),
    sa.Column('new_plan_id', sa.INTEGER(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('last_reset', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action_type', name='_user_action_uc')
    )
    op.drop_table('credit_wallets')
    # ### end Alembic commands ###
