from datetime import datetime
from app.extensions import db

class JobPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    company = db.Column(db.String(200), nullable=False)
    location = db.Column(db.String(200))
    platform = db.Column(db.String(50))
    job_url = db.Column(db.String(500), unique=True, nullable=False)
    description = db.Column(db.Text)
    posted_at = db.Column(db.DateTime)
    ingested_at = db.Column(db.DateTime, default=datetime.utcnow)

class JobMatch(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    job_id = db.Column(db.Integer, db.ForeignKey('job_post.id'), nullable=False)
    match_score = db.Column(db.Float)
    is_applied = db.Column(db.Boolean, default=False)
    is_scheduled = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    job = db.relationship('JobPost', backref='matches')

class Application(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    job_id = db.Column(db.Integer, db.ForeignKey('job_post.id'), nullable=False)
    status = db.Column(db.String(50), default='Scheduled')
    applied_at = db.Column(db.DateTime)
    status_message = db.Column(db.String(255))
    error_message = db.Column(db.Text)
    screenshot_path = db.Column(db.String(255))

class LinkedInJob(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    linkedin_job_id = db.Column(db.String(255), unique=True, nullable=False)
    title = db.Column(db.String(255), nullable=False)
    company = db.Column(db.String(255), nullable=False)
    location = db.Column(db.String(255))
    description = db.Column(db.Text)
    job_url = db.Column(db.String(500), nullable=False)
    is_easy_apply = db.Column(db.Boolean, default=False)
    salary_range = db.Column(db.String(100))
    employment_type = db.Column(db.String(50))
    seniority_level = db.Column(db.String(50))
    posted_at = db.Column(db.DateTime)
    scraped_at = db.Column(db.DateTime, default=datetime.utcnow)
    is_active = db.Column(db.Boolean, default=True)

class NaukriJob(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    naukri_job_id = db.Column(db.String(255), unique=True, nullable=False)
    title = db.Column(db.String(255), nullable=False)
    company = db.Column(db.String(255), nullable=False)
    location = db.Column(db.String(255))
    experience_required = db.Column(db.String(100))
    salary_range = db.Column(db.String(100))
    job_url = db.Column(db.String(500), nullable=False)
    description = db.Column(db.Text)
    skills_required = db.Column(db.Text)
    posted_at = db.Column(db.String(100))
    scraped_at = db.Column(db.DateTime, default=datetime.utcnow)
    is_active = db.Column(db.Boolean, default=True)

class JobAlert(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    keywords = db.Column(db.Text, nullable=False)
    location = db.Column(db.String(255))
    platforms = db.Column(db.Text)
    frequency = db.Column(db.String(50), default='instant')
    is_active = db.Column(db.Boolean, default=True)
    last_checked = db.Column(db.DateTime, default=datetime.utcnow)
    email_enabled = db.Column(db.Boolean, default=True)
    sms_enabled = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
